[package]
name            = "disktest"
description     = "Hard Disk and Solid State Disk tester"
version         = "1.3.1"
homepage        = "https://bues.ch/h/disktest"
license         = "GPL-2.0-or-later"
readme          = "README.md"
repository      = "https://bues.ch/cgit/disktest.git"
authors         = ["Michael Buesch <m@bues.ch>"]

categories      = ["command-line-utilities", "filesystem", "hardware-support"]
keywords        = ["disk", "HDD", "SSD", "flash", "SD-card"]

exclude         = ["/maintenance/", "/testfile*"]

edition         = "2018"

[dependencies]
anyhow          = "1.0.34"
clap            = "2.33.3"
crc             = "1.8.1"
hhmmss          = "0.1.0"
libc            = "0.2.80"
num_cpus        = "1.13.0"
rand            = "0.7.3"
rand_chacha     = "0.2.2"
rust-crypto     = "0.2.36"
signal-hook     = "0.1.16"
tempfile        = "3.1.0"

[target.'cfg(target_os="windows")'.dependencies]
winapi          = "0.3.9"

[profile.dev]
lto             = "thin"
opt-level       = 2

[profile.release]
lto             = "thin"
panic           = "abort"

[profile.test]
lto             = "thin"
opt-level       = 2

[profile.bench]
lto             = "thin"

# vim: ts=4 sw=4 expandtab
